In [48]:
a = torch.randn(2,3,256,256)
a.shape

torch.Size([2, 3, 256, 256])

In [49]:
a = a.view(2,3,2,128,2,128).permute(0,1, 2,4,3,5).contiguous().view(2,-1,128,128)
a.shape

torch.Size([2, 12, 128, 128])

In [36]:
# a = a.conti.view(-1, 64,64,3)
# a.shape

In [50]:
conv2d = nn.Conv2d(
    12,
    32*4,
    kernel_size=3,
    padding=1,
    stride=2,
    bias=False,
    groups=4
)

In [51]:
out = conv2d(a)
out.shape

torch.Size([2, 128, 64, 64])

In [52]:
out = out.view(2, 32,4, 64,64)
out.shape

torch.Size([2, 32, 4, 64, 64])

In [53]:
out = out.view(2,32, 2,2,64,64).permute(0,1,2,4,3,5)
out.shape

torch.Size([2, 32, 2, 64, 2, 64])

In [54]:
out = out.contiguous().view(2,32,128,128)
out.shape

torch.Size([2, 32, 128, 128])

In [1]:
import torch
import torch.nn as nn
import sys
sys.path.append('../')

In [2]:
from lib.model import resnet18_group


In [3]:
model = resnet18_group(pretrained=False)

In [4]:
x = torch.randn(2,3,224,224)
B, C, H, W = x.shape
x = x.view(B, C, 2, int(H/2), 2, int(W/2)).permute(0,1,2,4,3,5).contiguous().view(2,C*4,int(H/2),int(W/2))
x.shape


torch.Size([2, 12, 112, 112])

In [5]:
out = model(x)

torch.Size([2, 512, 14, 14])
torch.Size([2, 256, 14, 14])
torch.Size([2, 512, 7, 7])


In [1]:
# model

In [3]:
import torch
drop_path_rate = 0.1
depth=8
dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]

In [4]:
dpr

[0.0,
 0.014285714365541935,
 0.02857142873108387,
 0.04285714402794838,
 0.05714285746216774,
 0.0714285746216774,
 0.08571428805589676,
 0.10000000149011612]

In [7]:
import torch
torch.ones((2,3)) * 0.01

tensor([[0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100]])

In [10]:
a = torch.tensor([[1,2,3], [1,1,1]])
b = torch.tensor([2,3,3])

In [11]:
a*b

tensor([[2, 6, 9],
        [2, 3, 3]])

In [27]:
import torch
import torch.nn as nn
class Sample(nn.Module):
  def __init__(self):
    super(Sample, self).__init__()
    self.gamma = nn.Parameter(torch.randn((1,2)))
  
  def forward(self, x):
    return self.gamma(x)

In [28]:
net = Sample()

In [30]:
net.gamma


Parameter containing:
tensor([[0.6556, 0.9246]], device='cuda:0', requires_grad=True)

In [25]:
net.cuda()

Sample()

tensor([ 0.7511,  0.1289, -0.0291,  1.1733,  0.9194], device='cuda:0')